#!/usr/bin/env python3
"""Build agent context; --check validates links, navigation and bundle freshness."""
import argparse
import json
from pathlib import Path
import re
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ("docs/agents.md", "spec/0001-boundary.md", "spec/core.md", "spec/plugin.md", "spec/e2ee.md", "crypto/README.md", "conformance/e2ee.md", "spec/a2a.md", "spec/audit.md", "VALIDATION.md", "schemas/discovery.schema.json", "schemas/core.schema.json", "schemas/e2ee.schema.json")


def source(path):
    resolved = (ROOT / unquote(path)).resolve()
    if not resolved.is_relative_to(ROOT) or not resolved.is_file():
        raise ValueError("Missing or out-of-repository path: " + path)
    return resolved


def validate():
    index = json.loads(source("agent-index.json").read_text())
    for key in ("entrypoint", "instructions", "compact_index", "full_context"):
        source(index[key])
    documents = {entry["path"] for entry in index["documents"]}
    for path in documents:
        source(path)
    for paths in index["reading_paths"].values():
        for path in paths:
            if path not in documents:
                raise ValueError("Reading path is not indexed: " + path)
    for command in index["commands"].values():
        if command["cwd"] != "." or not command["side_effects"] or not isinstance(command["argv"], list):
            raise ValueError("Incomplete command metadata")
        for arg in command["argv"]:
            if arg.endswith(".py"):
                source(arg)
    files = list(ROOT.rglob("*.md"))
    for file in files:
        body = re.sub(r"```.*?```", "", file.read_text(), flags=re.S)
        for target in re.findall(r"\[[^\]]*\]\(([^\s)]+)\)", body):
            link = urlsplit(target)
            if link.scheme or link.netloc or not link.path:
                continue
            relative = (file.parent / unquote(link.path)).relative_to(ROOT)
            source(str(relative))
    for target in re.findall(r"\]\((https://raw\.githubusercontent\.com/[^)]+)\)", source("llms.txt").read_text()):
        prefix = "https://raw.githubusercontent.com/tincan-ai/protocol/main/"
        if not target.startswith(prefix):
            raise ValueError("Unexpected raw documentation origin")
        source(target[len(prefix):])


def bundle():
    parts = ["# Tincan protocol — agent context\n\nGenerated by scripts/build-agent-docs.py. Do not edit directly.\nDraft 0.1; source specifications remain authoritative. Relative links resolve\nfrom each named source file. A2A is a proposal, not a shipped capability.\n\nFor scoped reading use agent-index.json or llms.txt.\n"]
    for path in SOURCES:
        body = source(path).read_text().rstrip()
        if path.endswith(".json"):
            body = "```json\n" + body + "\n```"
        parts.append("\n---\n\nSource: " + path + "\n\n" + body + "\n")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "llms-full.txt"
    expected = bundle()
    if args.check:
        if not output.exists() or output.read_text() != expected:
            raise SystemExit("Stale agent bundle; run python3 scripts/build-agent-docs.py")
    else:
        output.write_text(expected)
    validate()
    print("Agent index, local links and context bundle verified")


if __name__ == "__main__":
    main()
